version: '3.7'
services:
  pocketbase:
    image: spectado/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - '8090:80'
    volumes:
      - ./pb/data:/pb_data
      - ./pb/hooks:/pb_hooks
      - ./pb/public:/pb_public
      - ./pb/migrations:/pb_migrations
